### ISSUE TITLE
Add some help in "Callcentric" channel configuration page

### ISSUE THREAD

**Issue by waj** [instedd/verboice#426]
Get some inspiration from: http://www.voip-sip-sdk.com/p_54-callcentric-setup-voip.html

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/verboice/issue/426
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-01-31 15:30:03+00:00

**Comment by pmallol** [comment]
Ok in version 2.4.1-1
