### ISSUE TITLE
"Write variable" step

### ISSUE THREAD

**Issue by waj** [instedd/verboice#510]
Create a new step that stores a literal for a selected variable. The step UI shows a dropdown with the list of variables and has a textbox for the value. Values can be any string, but numbers should still be treated as such for gt and lt comparisons in branches, and should also be exported as numbers in CSV and fusion tables.  @jkicillof : we'll need an icon for this

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/verboice/issue/510
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-10-14 19:12:57+00:00

**Comment by nditada** [comment]
There's a mismatch between the design and the implemented UI. Let's discuss what to adjust. Also, "Request" is a bit confusing as the label for the name of the Variable.

**Comment by nditada** [comment]
- [ ] Change "Request" label to "Variable name"
- [ ] Change "to be equal to" to "New value"
