### ISSUE TITLE
Error when uploading audio files

### ISSUE THREAD

**Issue by waj** [instedd/verboice#513]
It's working fine for the owner of the project but not for a shared admin. The code is looking for the projects in the user's projects and not including the shared ones.
---
- Imported from BitBucket: https://bitbucket.org/instedd/verboice/issue/513
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-10-20 23:04:44+00:00

**Comment by mmuller** [comment]
Ok in version 3.0-pre1
