### ISSUE TITLE
Language is not exposed as a variable in call flow

### ISSUE THREAD

**Issue by waj** [instedd/verboice#578]
In Branches, and as arguments or returns of External Services, no Language is shown.
Expected - show Language as a variable in the flow
- To make language-specific branching in an otherwise shared flow
- To allow storing it in, or loading it from, an external service.
---
- Imported from BitBucket: https://bitbucket.org/instedd/verboice/issue/578
- Originally Reported By: edjez
- Originally Created At: 2014-11-19 08:52:25+00:00

**Comment by pmallol** [comment]
Ok in Version 3.0-pre2
