### ISSUE TITLE
Trigger Hub Action from Step

### ISSUE THREAD

**Issue by nditada** [instedd/verboice#608]
We need a new step called "External Action" that shows a list of available actions. When the user selects an action, the step needs to show the list of parameters and allow the user to assign either a literal or select a variable.

**Comment by nditada** [comment]
There's a small bug with this: when I click in the button to open the popup to select the hub action, the frame is initially loaded with the verboice page itself. Closing it and opening it again solves the issue.

**Comment by asterite** [comment]
It turned out to be a bug in alto_guisso_rails. The fix is [here](https://github.com/instedd/alto_guisso_rails/commit/9d4aa030f4e02ce63014aa7519078780e2eb25d0).

Now we only need to update this in all apps using alto_guisso_rails.

**Comment by asterite** [comment]
Updated [Verboice](https://github.com/instedd/verboice/commit/2f710b89857b46b3cda401e73d2493d9c637cc02).
