### ISSUE TITLE
Set fail reason of unanswered calls to no-answer

### ISSUE THREAD

**Issue by ggiraldez** [instedd/verboice#620]
This is on version 2.4.3.

Outgoing calls that are not answered are marked as 'failed' with reason 'error' in the call log, while the final status reported to the user callback is 'no-answer'. This was raised by Justin Hayes:

> There is an ongoing issue where many calls are marked as "failed (error)" in the web-based call logs UI. These calls do not appear in Didlogic's history, but I notice that they are identified as "no answer" in the call status updates we receive from Verboice to our server.  I assume this is typical behavior if the local cellphone carrier terminates a call after sixty seconds of inactivity. Would it be possible to improve the reporting for these calls so they are indicated as "no answer" in the web UI? It would be helpful to reduce this source of confusion between real call failures and false positives.

For the Asterisk broker, the session state transition is always dialing(reject) -> failed, but the Reason reported is different depending on whether the remote peer rejects the call (failed), or the local asterisk times out (no_answer). Asterisk session timeout is set in asterisk_broker:dispatch(), and is currently 60 seconds. Need to check the behaviour for the Twilio broker.

**Comment by pmallol** [comment]
Tested with both channel and callee numbers from Callcentric. The callee number had to be configured in Callcentric > Preferences > General so that the value for "Send un-answered calls to user
unavailable message after:" is 60 seconds.

Working ok in version 2.4.4
