### ISSUE TITLE
Deleting first step of call flow rearranges sub call flows

### ISSUE THREAD

**Issue by edjez** [instedd/verboice#626]
When deleting the first step of the first subcallflow in the call flow designer, the whole first sub-flow got rearranged to be the last sub-call-flow on the designer. 
This caused the call to start at the sub-flow remaining at the top, with no way to rearrange than to delete and recreate the whole "stack" of flows.
Given multiple sub call flows it may be great to allow users to promote one to be the "first"/top one
![image](https://cloud.githubusercontent.com/assets/1182549/5770034/0abbfb96-9cd9-11e4-89e5-b3171abf4e80.png)

**Comment by mmuller** [comment]
Sub flows can be rearranged properly in version 3.0-pre1
