### ISSUE TITLE
Issues when importing a call flow with external services

### ISSUE THREAD

**Issue by nditada** [instedd/verboice#635]
External services are exported inside the .zip when a call flow is exported. However, when importing that .zip in a different project, something (manifest settings?) are left in an inconsistent state and calls failed with an error. Writing the settings in the config of the manifest does not solve the issue (see example at https://poirot-verboice-cdc.instedd.org/activities/0784667f-ac50-4127-bba6-4bdbc9cdb8d6)

Strangely enough, adding a new instance of the same offending step from that same external service in the call flow, solves the issue. Even after deleting that step, the flow remains working fine.

**Comment by pmallol** [comment]
The external service is imported just fine, but there is a new issue in which the resources from the call flow are exported just when the checkbox "include audio recordings" is checked, even if its type is 'text to speech'.

**Comment by spalladino** [comment]
Closing this issue, as external services are working. The issue with the recordings is moved to https://github.com/instedd/verboice/issues/764.
