### ISSUE TITLE
'Previous' button in Calls redirects to a nonexisting page

### ISSUE THREAD

**Issue by pmallol** [instedd/verboice#638]
Found in version 2.5-pre2
1. Navigate to Calls
2. Click on the light grey left arrow in the call log paginator control 

Obtained: user is redirected to page=0 which does not exist.

Expected: the button should be disabled.

![screen shot 2015-01-27 at 11 53 25 am](https://cloud.githubusercontent.com/assets/9214460/5920442/5c725dfe-a61b-11e4-9be4-3782f3c9dd4a.png)

**Comment by spalladino** [comment]
Fixed as of 2.7.1
