### ISSUE TITLE
Forward Call Step should accept Variable as Forward-to number

### ISSUE THREAD

**Issue by edjez** [instedd/verboice#644]
For example, different users may have a different clinic number that they need to be referred to. Making that a variable in addition to just a literal allows a more flexible forwarding without setting up a hardcoded set of branches in the callflow.

![image](https://cloud.githubusercontent.com/assets/1182549/5931603/a06b5b94-a654-11e4-9c2c-de3dbf013ee2.png)

**Comment by edjez** [comment]
For example: setting a default clinic or nurse for different address book users to be referred to, or a dispatching hotline that sends to one of many phone numbers depending on health condition.

**Comment by mmuller** [comment]
Ok in version 3.0-pre2
