### ISSUE TITLE
Filtering phonebook by an empty value shows 2 entries

### ISSUE THREAD

**Issue by pmallol** [instedd/verboice#649]
Found in version 2.5-pre2

Precondition:
User has a Project and a Call Flow. Also, in the Calls tab, many calls from different contacts, some of them with numbers inside a variable called 'sticker_id' -4 digits the caller is asked to enter in the call flow- and the rest without any numbers.

1. Navigate to the Phone Book of the project
2. Filter by "sticker_id is equal to value (empty)" and click the checkmark
3. Click the Search button

Obtained: there are two entries found after the search.

Expected: either the search should be invalid (because the input field was empty) or it should show all contacts without a 'sticker_id' (e.g: same result as condition: "sticker_id is undefined").

![screen shot 2015-01-28 at 5 10 43 pm](https://cloud.githubusercontent.com/assets/9214460/5945899/a815bac6-a710-11e4-955b-f1edc03271a8.png)

**Comment by nditada** [comment]
@pmallol can you confirm that the "undefined" query returns a different result? If it return the same 2 entries, then this behaviour is correct.

**Comment by pmallol** [comment]
The "undefined" query returns all contacts without a sticker_id (including those two showed in the previous screenshot), as expected.

![screen shot 2015-02-11 at 6 02 17 pm](https://cloud.githubusercontent.com/assets/9214460/6156355/52755334-b218-11e4-91e0-e1b29c500662.png)

**Comment by pmallol** [comment]
Ok in version 2.5-pre4
