### ISSUE TITLE
Scheduled Calls are executed before the time span established

### ISSUE THREAD

**Issue by pmallol** [instedd/verboice#652]
Found in version 2.5-pre2

Precondition:
User has a Project and a Call Flow in which the callee is asked to enter 4 digits saved as **'sticker_id'**. In the Calls tab there are many calls from different contacts, three of them with 4 numbers inside the variable 'sticker_id' and the rest without any numbers.

1. Navigate to Scheduled Calls
2. Add a scheduled call
3. Enter a [name], select a call flow and channel and configure the schedule: ["Weekly on Wednesdays" from "15:00 to 8:00 on next day"] and a filter: ['sticker_id' > greater or equal to > value > 1]
4. Click on Save

Obtained: all three contacts with 'sticker_id' were called at 00:00 UTC and the calls lasted until 15:00 UTC. 

Expected: the three contacts with 'sticker_id' are called from 15:00 UTC to 8:00 on next day.

![screen shot 2015-01-29 at 11 33 42 am](https://cloud.githubusercontent.com/assets/9214460/5959187/b6cfd6c4-a7aa-11e4-9837-135983dba925.png)

![screen shot 2015-01-29 at 11 31 22 am](https://cloud.githubusercontent.com/assets/9214460/5959166/80a41cb8-a7aa-11e4-8bc1-00b9771ee281.png)

**Comment by romeroadrian** [comment]
The issue here is that the "Started" date is wrong, that date is when the call log was created and not when the call was actually started. Will fix this.

**Comment by pmallol** [comment]
Ok in version 2.5-pre3
