### ISSUE TITLE
Audio resource filename clash when importing call flow to other project

### ISSUE THREAD

**Issue by ggiraldez** [instedd/verboice#659]
When preparing blob resources, the broker names the files using just the resource GUID for Asterisk to consume. The problem is when importing a call flow into a different project, the GUID for the resource is the same for both projects.

Steps to reproduce:

1. Create call flow A in a project One
2. Add a play step to call flow A and use a blob (record/uploaded) resource
3. Save call flow A
4. Export call flow A
5. Create a new project Two and a call flow B in this new project
6. Import exported call flow A into call flow B
7. Replace the blob resource in call flow B with new audio
8. Make a call that uses call flow A

Results: the new audio is played when using both call flow A and B
Expected: call flow A retains the previous audio resource

Note: This does not happen with text resource since the project ID is used in addition to the GUID when naming the filename.

**Comment by pmallol** [comment]
Working ok in version 2.5-pre4
