### ISSUE TITLE
'Hang up' icon appears instead of the External Action step

### ISSUE THREAD

**Issue by pmallol** [instedd/verboice#664]
Found in version 2.5-pre3
1. Open Call flow
2. Add an 'External Action' step

Obtained: the icon in the right sidebar for the step corresponds to the 'Hang up' step

![screen shot 2015-02-13 at 4 47 55 pm](https://cloud.githubusercontent.com/assets/9214460/6194147/29c5cbce-b3a0-11e4-8f06-d88ee0d83150.png)

**Comment by mmuller** [comment]
'External action' step shows the correct icon in version 3.0-pre1
