### ISSUE TITLE
Queued calls from a contact appear inside all projects's phone books containing said number

### ISSUE THREAD

**Issue by pmallol** [instedd/verboice#667]
Found in version 2.5-pre4

Preconditions
User has Projects A and B. Both projects's phone books contain same contact phone number 'X'

1. Enqueue a call in Project A using phone number 'X' and setting "Not Before" to same day but a half hour later
2. Open Project B and navigate to Phone Book
3. Select phone number 'X' listed in the phone book
4. Click on Calls tab and choose "Scheduled calls"

Obtained: queued calls (including scheduled calls) in project A for phone number 'X' appear in project B's phone book for same contact number

**Comment by mmuller** [comment]
Ok in version 2.5-pre5
