### ISSUE TITLE
Verboice sends wrong requests to Guisso

### ISSUE THREAD

**Issue by mmuller** [instedd/verboice#669]
Found in version: 2.5-pre4

Hub actions couldn't invoked properly using an account recently created 

User email: mmuller+0215@manas.com.ar
Poirot activity: http://poirot-stg.instedd.org/activities/19142585-6c7b-4fd2-8adb-d073fddc2bb9

Obtained: The call fails and "Fatal Error: function_clause" is shown in the call log

**Comment by ggiraldez** [comment]
This is because of the way the token request is formed in Verboice. In `guisso.erl` the scope is constructed as an iolist() which is then incorrectly formatted when building the body of the request.
