### ISSUE TITLE
Fatal error in hub when an External Action step is executed 

### ISSUE THREAD

**Issue by pmallol** [instedd/verboice#670]
Found in version 2.5-pre4

1. Create a project with a [call flow A] and another project with a [call flow B]
2. Add to [call flow A]: 
     * a Play step with the message "This is call flow A" so it is easy to recognise later
     * an External Action step in which the action is to call call flow B through a [channel X] to a [number x]
3. Add to [call flow B]:
      * a Play step with the message "This is call flow B"
4. Enqueue a call for [call flow A] through [channel Y] to [number y]

Obtained: the enqueued call is executed, verboice calls [number y] and the user can listen to [call flow A], however the call finishes and the External Action step fails.
Poirot log: http://poirot-stg.instedd.org/activities/75a490c1-e07d-4a33-8304-98c481a4613c

Expected: the call is executed successfully, [number y] can listen to [call flow A] and after that call finishes [number x] receives a call with [call flow B]

**Comment by ggiraldez** [comment]
This is a bug in Erlang's json dependency. When encoding large integers it sometimes would return an error instead. For example, on a 32-bit system:

```
> json:encode({[{foo, 12345678901}]}).
{ok,<<"{\"foo\":12345678901}">>}
> json:encode({[{foo, 12345678901},{bar,{[]}}]}).
{error,failed_to_open_empty_map}
> json:encode({[{foo, 1234567890},{bar,{[]}}]}).
{ok,<<"{\"foo\":1234567890,\"bar\":{}}">>}
```

On 64-bit systems the same problem appears, only with bigger numbers.

**Comment by ggiraldez** [comment]
To test this, make sure the broker flow is recompiled. Ie, make some change in call flow A and save it.

**Comment by mmuller** [comment]
Ok in version 2.5-pre5
