### ISSUE TITLE
Queued calls through shared channel not showing up in Calls log

### ISSUE THREAD

**Issue by pmallol** [instedd/verboice#673]
Found in version 2.5-pre4

User A shared a channel to User B with admin permissions

As **User B**
1. Open a project
2. Enqueue a call: 
    *select a call flow and the channel shared by User A 
    *set 'Not before' to the next day at any time
3. Navigate to Channels
4. Select the channel shared as admin
5. Click on link 'View calls' located under 'Properties'

Obtained: the Queued calls tab indicated there are "No entries found" even when the channel's properties showed "1 queued call"

Expected: User B is able to see the queued calls from own projects with a shared channel

**Comment by ggiraldez** [comment]
Owner of the channel can see (and cancel) queued calls and all call logs using the channel. Other users can see queued calls and call logs if they can access the project associated with the call (owner or permission).

**Comment by mmuller** [comment]
Ok in v2.5-pre5
