### ISSUE TITLE
User with admin permissions for shared channel can see call logs from other projects in CSV

### ISSUE THREAD

**Issue by pmallol** [instedd/verboice#674]
Found in version 2.5-pre4

Preconditions:
User A shares a [channel X] to User B with admin permissions.
User B executed and enqueued calls with [channel X].

As **User B**
1. Navigate to Channels
2. Open [channel X]
3. 'Download as CSV'

Obtained: the CSV is downloaded but shows call logs for projects not owned by nor shared with User B.

Expected: the CSV shows only call logs for projects owned by and shared to User B

**Comment by ggiraldez** [comment]
Owner of the channel can see (and cancel) queued calls and all call logs using the channel. Other users can see queued calls and call logs if they can access the project associated with the call (owner or permission).

**Comment by mmuller** [comment]
Ok in version 2.5-pre5
