### ISSUE TITLE
'Started' column in CSV shows the time call was enqueued

### ISSUE THREAD

**Issue by pmallol** [instedd/verboice#678]
Found in version 2.5-pre4

1. Open a project
2. Enqueue a call: 
    *select a call flow and [channel X]
    *set 'Not before' to the same day, some minutes after the actual time
3. After the call was executed navigate to Channels
4. Open [channel X]
5. 'Download as CSV'

Obtained: in the CSV the column 'Started' shows the time the call was enqueued and not the time the call was executed and 'Duration' equals the sum of the time the call was enqueued and the minutes the call lasted.

Expected: the column 'Started' indicates de time the call was executed and 'Duration' the amount of time the call lasted.

**Comment by mmuller** [comment]
Ok in Version 2.5-pre5
