### ISSUE TITLE
'Select' button displays url when selecting an External Action

### ISSUE THREAD

**Issue by mmuller** [instedd/verboice#681]
Found in version: 1.6.2

Steps:
Go to create a Reminder
Press the button '+' to add a new message
Choose 'External Action'
Select some Action

Obtained:
-'Select' button displays url when selecting an External Action

![screen shot 2015-03-11 at 5 06 23 pm](https://cloud.githubusercontent.com/assets/518152/6606041/7405310c-c813-11e4-9870-87e29f42946f.png)

**Comment by bcardiff** [comment]
This dialog is managed by Hub's code
