### ISSUE TITLE
Contacts cannot be manually created

### ISSUE THREAD

**Issue by mmuller** [instedd/verboice#701]
Found in version: 2.6-pre1-2-g67221f1

Steps:
Go to the Phone Book
Click 'New contact'
Fill the field 'Phone number' with a numeric value
Press the icon '+'
Press the save button

Obtained:
The new contact is not shown in the contacts listing

Expected:
The new contact is included in the contacts listing

**Comment by pmallol** [comment]
Ok in version 2.6.1-pre1
