### ISSUE TITLE
Consecutive outgoing calls via local appliance ocassionally fail

### ISSUE THREAD

**Issue by spalladino** [instedd/verboice#705]
When using a local appliance (such as Voiceblue), placing two outgoing calls may cause the second one to fail with a "channel congestion" error.

**Comment by spalladino** [comment]
Increase the time between two outgoing calls through the same channel

**Comment by spalladino** [comment]
Fixed in 999edd7c2b66e6d91e7c60f46d31797624f96c08

**Comment by pmallol** [comment]
Ok in version 2.6.1-pre1
