### ISSUE TITLE
Cannot manually add variable in phone book

### ISSUE THREAD

**Issue by pmallol** [instedd/verboice#711]
Found in version 2.6.1-pre1 (also present in production v.2.5.2)

1. Create a Project
2. Navigate to the Phone Book tab
3. Click on Manage Phone Book's columns
4. Add new variable and Confirm

Obtained:
Page is not found. 404 error
 
Expected:
User should be able to add variables to phone book

**Comment by spalladino** [comment]
@pmallol could not reproduce
