### ISSUE TITLE
Alert icon is not clickable in steps in call flow

### ISSUE THREAD

**Issue by spalladino** [instedd/verboice#730]
The warning alert icon in the top right cannot be clicked to select a step in a call flow.
<img width="76" alt="screen shot 2016-02-15 at 4 51 13 pm" src="https://cloud.githubusercontent.com/assets/429604/13058820/7dcc3c46-d404-11e5-8000-19bd8f13e9a1.png">

**Comment by mmuller** [comment]
Alert icon can be clicked properly in version 3.0-pre1
