### ISSUE TITLE
Cannot copy phone number from address book

### ISSUE THREAD

**Issue by spalladino** [instedd/verboice#733]
In the Phone Book list, when selecting a contact's phone number by "painting" it with the cursor, the browser leaves the page and navigates to the contact's details page upon mouseUp.

**Comment by mmuller** [comment]
Now, in version 3.0-pre1 the reported behavior was not changed. After painting a phone number, the app navigates to the contact's details page.

**Comment by spalladino** [comment]
In `3.0-pre2` the area for copying without navigating to the contact details (ie the area where the cursor is `text` and not `pointer`) is enlarged around the phone number

**Comment by mmuller** [comment]
Working as expected. Tested in version `3.0-pre2`.
