### ISSUE TITLE
Timeline for scheduled calls is rendered multiple times upon validation errors

### ISSUE THREAD

**Issue by spalladino** [instedd/verboice#736]
- Click "add new scheduled call" twice
- There should be two blue "scheduled call" boxes open
- Attempt to save the second one several times, without entering any values
- A validation error will be displayed for the 2nd one
- The first one will show a timeline for each time the second one was attempted to be saved

<img width="630" alt="screen shot 2016-02-15 at 5 02 00 pm" src="https://cloud.githubusercontent.com/assets/429604/13059026/189c1ba0-d406-11e5-84af-0c8c6dbc4d7a.png">

**Comment by spalladino** [comment]
Fixed in 98a792c by preventing more than a single "new" scheduled calls form being displayed at a time.

**Comment by mmuller** [comment]
Ok in version 3.0-pre1
