### ISSUE TITLE
Editing a "detect language" text option always redirects to the default language

### ISSUE THREAD

**Issue by spalladino** [instedd/verboice#737]
- In a project with 2 languages (eg English and Spanish, being English the default), add a Detect Language step to a call flow and edit its messages.
- When clicking on the "Spanish" arrow to edit that message, the "English" text is always selected, when the Spanish one should be.

<img width="304" alt="screen shot 2016-02-15 at 5 28 39 pm" src="https://cloud.githubusercontent.com/assets/429604/13059560/bd5dce1a-d409-11e5-87fd-daa113654f68.png">

<img width="273" alt="screen shot 2016-02-15 at 5 28 45 pm" src="https://cloud.githubusercontent.com/assets/429604/13059562/bfb18dc8-d409-11e5-86f9-b315a458b0be.png">

**Comment by mmuller** [comment]
Working as expected in version 3.0-pre1
