### ISSUE TITLE
"Last activity" column in phonebook

### ISSUE THREAD

**Issue by nditada** [instedd/verboice#741]
Add a column with the "last activity" date for each phonenumber in the phonebook, showing the date where the last call to that entry was made or received. Allow sorting by that column (#740)

**Comment by mmuller** [comment]
After executing a Call the  `Last activity` column is not filled. Last activity is not being displayed in the Phonebook.
Tested on version 2.7-55-gb2a19c3

**Comment by mmuller** [comment]
Incoming calls are not being displayed in the `Last activity` column in version `3.0-pre2`.
Preconditions:
The Channel `C` has a Call Flow `CF` configured for incoming calls.
The Phone Number `PN` is a contact stored in the Phone Book. 

Reproduce steps:
Using the Phone Number `PN` call to Verboice Channel `C`. 
Navigate to the Phone Book.
Observe the last activity displayed for the Phone Number `PN`.

Obtained:
The `Last activity` column doesn't include information about the last received call.

**Comment by mmuller** [comment]
There was an issue in Callcentric, this feature was implemented correctly.
