### ISSUE TITLE
Add option to send session variables in status callback

### ISSUE THREAD

**Issue by spalladino** [instedd/verboice#744]
Since there is no direct way to extract the session variables from a call, extend the status callback to support including all session variables in the callback. This options should be disabled by default.

Consider including the variables in the query string vs changing the callback to a POST request to include the variables in the body in JSON format.

**Comment by spalladino** [comment]
Variables are sent in the callback query string, same as the additional callback parameters that can be configured via API. Note that all of the contact's variables are sent, not just those set on the call.

**Comment by mmuller** [comment]
Working as expected in version 2.7-55-gb2a19c3
