### ISSUE TITLE
Paging in call logs breaks paging in phonebook

### ISSUE THREAD

**Issue by spalladino** [instedd/verboice#750]
1. Navigate to a project's phonebook
2. Note that the pager (if there is more than a single page) correctly points to page 2 of the project's contacts by hovering on the next page button
3. Navigate to call logs
4. Move to the next page
5. Go back to a phonebook
6. Note that the pager's _next page_ URL now points to the call log listings, thus breaking the phonebook's pager

<img width="569" alt="screen shot 2016-10-11 at 11 26 35 am" src="https://cloud.githubusercontent.com/assets/429604/19274188/b87c7f6a-8fa5-11e6-9839-683fa64dc611.png">

Both call logs and the phonebook are implemented using the same `paginate` helper method, though the former uses listings and the latter does not. Could be caused by listings making use of a session parameter to store current listing information, and using it in the `paginate` helper?

**Comment by spalladino** [comment]
cc @bcardiff

**Comment by bcardiff** [comment]
@spalladino overriding `#param_page` in the listing https://github.com/manastech/listings/blob/master/lib/listings/base.rb#L31 can be a workaround for this issue. There might be more params that collide though.

**Comment by mmuller** [comment]
Ok in version 3.0-pre1
