### ISSUE TITLE
Error when searching by defined variable in phonebook after a value search

### ISSUE THREAD

**Issue by spalladino** [instedd/verboice#753]
1. Navigate to a project's phonebook
2. Create a new filter by a variable being equal to a certain value (ex foo is equal to value 42)
3. Hit search
4. *Change* that filter (do not remove it and create a new one) to the variable being defined (ex foo is defined)
5. Hit search

The server returns a 500 error.

Found 2.7.1

**Comment by mmuller** [comment]
Working as expected in version 2.7-55-gb2a19c3
