### ISSUE TITLE
update Africa's Talking channel

### ISSUE THREAD

**Issue by manumoreira** [instedd/verboice#894]
Testing a channel recently we realized that verboice code is not handling the case
`calSessionState = "Answered"`
We are receiving this first request 
{
  "callSessionState": "Answered",
  "sessionId": "ATVId_11163e2ea9a58f3a7999fecda8eeb43a",
  "callerCountryCode": "256",
  "callerCarrierName": "Airtel",
  "isActive": "1",
  "callStartTime": "2021-10-13+19:10:16",
  "direction": "Outbound",
  "destinationNumber": "+2563XXXX0647",
  "callerNumber": "+2567XXXX9081"
}
And we are answering `OK`instead of sending the first step of the flow

**Comment by matiasgarciaisaia** [comment]
Fixed in #895
