### ISSUE TITLE
Support newer MySQL versions

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/verboice#897]
Verboice is using MySQL 5.6 in production, which [is getting deprecated by AWS RDS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.VersionMgmt.Deprecation56).

We should ensure that Verboice supports migrating to _at least_ MySQL 5.7. Supporting MySQL 8.0 would be best.

**Comment by matiasgarciaisaia** [comment]
[AWS RDS is dropping support for MySQL 5.7 on February 29th.](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MySQL.Concepts.VersionMgmt.html)

We should upgrade Guisso to ensure it works with MySQL 8+, in order to be able to migrate the production DB.

**Comment by ysbaddaden** [comment]
Oh my.
