### ISSUE TITLE
Displaying CNAM caller ID to outgoing calls 

### ISSUE THREAD

**Issue by slay1** [instedd/verboice#901]
hello is there a way i can add name characters to out going call and a custom CID please help

**Comment by matiasgarciaisaia** [comment]
Hi there!

Verboice doesn't support setting an alphanumeric CNAM caller ID.

You may be able to change Verboice's code to be able to specify a CallerID, but it will work or not depending on the channel (I think Asterisk doesn't support the feature, Twilio may support it depending on a few restrictions...).

So we won't probably implement this.
