### ISSUE TITLE
Optimize usage of address book in Verboice

### ISSUE THREAD

**Issue by manumoreira** [instedd/verboice#944]
For Verboice clients that drive Verboice programmatically, the address book is an unused feature that penalizes their performance

**Comment by matiasgarciaisaia** [comment]
Here's [the loop that traverses the whole address book](https://github.com/instedd/verboice/blob/d55a48da4188a8684889f2c61fe98f5c67335984/app/controllers/projects_controller.rb#L120-L153) for the project, which can grow to be large when using Surveda (we got +2M contacts some times).

This is, however, not used during normal Survda operation - that code is only used when queueing calls from the Project view page in Verboice itself (`/projects/:id`), and not via the API.

**Comment by matiasgarciaisaia** [comment]
I've just confirmed in Surveda Africa (running Verboice 3.5.1) that queueing a call from Projects (with 86k contact addresses) takes ~5.2 seconds (spending 5 seconds [in this first loop](https://github.com/instedd/verboice/blob/d55a48da4188a8684889f2c61fe98f5c67335984/app/controllers/projects_controller.rb#L124-L127) - of which "only" 450ms where in ActiveRecord), but queuing a call in that same project via Surveda only took 260ms.

So there's an optimization to be done in the Project Controller, but it's not a major issue for Surveda itself.

**Comment by anaPerezGhiglia** [comment]
closed by #945
